gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: '%env(int:REFRESH_TOKEN_TTL)%'
    ttl_update: '%env(bool:REFRESH_TOKEN_UPDATE_TTL)%'
    token_parameter_name: 'refreshToken'
