vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        users:
            uri_prefix:         /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        workspaces:
            uri_prefix:         /images/workspaces
            upload_destination: '%kernel.project_dir%/public/images/workspaces'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        settings:
            uri_prefix:         /images/settings
            upload_destination: '%kernel.project_dir%/public/images/settings'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
