<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327012628 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attendance (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, date DATE NOT NULL, check_in_at DATETIME DEFAULT NULL, check_out_at DATETIME DEFAULT NULL, is_late TINYINT NOT NULL, left_early TINYINT NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, employee_id INT NOT NULL, UNIQUE INDEX UNIQ_6DE30D91B5B48B91 (public_id), INDEX IDX_6DE30D918C03F15C (employee_id), UNIQUE INDEX unique_employee_date (employee_id, date), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE closure (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, name VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, created_at DATETIME NOT NULL, workspace_id INT NOT NULL, UNIQUE INDEX UNIQ_48078DD1B5B48B91 (public_id), INDEX IDX_48078DD182D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE employee (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(50) DEFAULT NULL, qr_token VARCHAR(64) NOT NULL, active TINYINT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, workspace_id INT NOT NULL, user_id INT DEFAULT NULL, shift_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_5D9F75A1B5B48B91 (public_id), UNIQUE INDEX UNIQ_5D9F75A11AE26361 (qr_token), INDEX IDX_5D9F75A182D40A1F (workspace_id), UNIQUE INDEX UNIQ_5D9F75A1A76ED395 (user_id), INDEX IDX_5D9F75A1BB70BC0E (shift_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE leave_request (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, date DATE NOT NULL, reason LONGTEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, reviewed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, employee_id INT NOT NULL, UNIQUE INDEX UNIQ_7DC8F778B5B48B91 (public_id), INDEX IDX_7DC8F7788C03F15C (employee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE shift (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, name VARCHAR(255) NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, workspace_id INT NOT NULL, UNIQUE INDEX UNIQ_A50B3B45B5B48B91 (public_id), INDEX IDX_A50B3B4582D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE subscription (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, plan VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, paddle_subscription_id VARCHAR(255) DEFAULT NULL, paddle_customer_id VARCHAR(255) DEFAULT NULL, current_period_end DATETIME DEFAULT NULL, canceled_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, workspace_id INT NOT NULL, UNIQUE INDEX UNIQ_A3C664D3B5B48B91 (public_id), UNIQUE INDEX UNIQ_A3C664D382D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, google_id VARCHAR(255) DEFAULT NULL, apple_id VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_8D93D649B5B48B91 (public_id), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE workspace (id INT AUTO_INCREMENT NOT NULL, public_id BINARY(16) NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, owner_id INT NOT NULL, UNIQUE INDEX UNIQ_8D940019B5B48B91 (public_id), INDEX IDX_8D9400197E3C61F9 (owner_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE workspace_setting (id INT AUTO_INCREMENT NOT NULL, ip_restriction_enabled TINYINT NOT NULL, allowed_ips JSON DEFAULT NULL, timezone VARCHAR(64) NOT NULL, locale VARCHAR(5) NOT NULL, workspace_id INT NOT NULL, UNIQUE INDEX UNIQ_4749539382D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D918C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE closure ADD CONSTRAINT FK_48078DD182D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A182D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1BB70BC0E FOREIGN KEY (shift_id) REFERENCES shift (id)');
        $this->addSql('ALTER TABLE leave_request ADD CONSTRAINT FK_7DC8F7788C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE shift ADD CONSTRAINT FK_A50B3B4582D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D382D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id)');
        $this->addSql('ALTER TABLE workspace ADD CONSTRAINT FK_8D9400197E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE workspace_setting ADD CONSTRAINT FK_4749539382D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id)');
        $this->addSql('ALTER TABLE daily_brew_attendance_batches DROP FOREIGN KEY `FK_22FA5C7282D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_attendance_batches DROP FOREIGN KEY `FK_22FA5C72A76ED395`');
        $this->addSql('ALTER TABLE daily_brew_attendances DROP FOREIGN KEY `FK_CD680F1C82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_attendances DROP FOREIGN KEY `FK_CD680F1C8C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_attendances DROP FOREIGN KEY `FK_CD680F1CA76ED395`');
        $this->addSql('ALTER TABLE daily_brew_attendances DROP FOREIGN KEY `FK_CD680F1CF39EBE7A`');
        $this->addSql('ALTER TABLE daily_brew_demo_sessions DROP FOREIGN KEY `FK_8201C815A76ED395`');
        $this->addSql('ALTER TABLE daily_brew_employee_attendance_batches DROP FOREIGN KEY `FK_5CAC43841D9718B8`');
        $this->addSql('ALTER TABLE daily_brew_employee_attendance_batches DROP FOREIGN KEY `FK_5CAC43848C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations DROP FOREIGN KEY `FK_1C4A4D2543575BE2`');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations DROP FOREIGN KEY `FK_1C4A4D255DA0FB8`');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations DROP FOREIGN KEY `FK_1C4A4D2582D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations DROP FOREIGN KEY `FK_1C4A4D258C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_employee_roles DROP FOREIGN KEY `FK_63052DE68C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_employee_roles DROP FOREIGN KEY `FK_63052DE6D60322AC`');
        $this->addSql('ALTER TABLE daily_brew_employee_salaries DROP FOREIGN KEY `FK_45472EAE82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_employee_salaries DROP FOREIGN KEY `FK_45472EAE8C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_employee_scores DROP FOREIGN KEY `FK_4BEC1C03456C5646`');
        $this->addSql('ALTER TABLE daily_brew_employee_scores DROP FOREIGN KEY `FK_4BEC1C03990BEA15`');
        $this->addSql('ALTER TABLE daily_brew_employee_templates DROP FOREIGN KEY `FK_BFEBC2EF56839BCF`');
        $this->addSql('ALTER TABLE daily_brew_employee_templates DROP FOREIGN KEY `FK_BFEBC2EF8C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_employees DROP FOREIGN KEY `FK_370C3B6F82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_employees DROP FOREIGN KEY `FK_370C3B6FA76ED395`');
        $this->addSql('ALTER TABLE daily_brew_employees DROP FOREIGN KEY `FK_370C3B6FBB70BC0E`');
        $this->addSql('ALTER TABLE daily_brew_employees DROP FOREIGN KEY `FK_370C3B6FCC26EB02`');
        $this->addSql('ALTER TABLE daily_brew_evaluation_criterias DROP FOREIGN KEY `FK_F5194DE782D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_evaluation_criterias DROP FOREIGN KEY `FK_F5194DE7A76ED395`');
        $this->addSql('ALTER TABLE daily_brew_evaluation_template_criterias DROP FOREIGN KEY `FK_AC46DABB5DA0FB8`');
        $this->addSql('ALTER TABLE daily_brew_evaluation_template_criterias DROP FOREIGN KEY `FK_AC46DABB990BEA15`');
        $this->addSql('ALTER TABLE daily_brew_evaluation_templates DROP FOREIGN KEY `FK_1B36534F82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_evaluation_templates DROP FOREIGN KEY `FK_1B36534FA76ED395`');
        $this->addSql('ALTER TABLE daily_brew_leave_requests DROP FOREIGN KEY `FK_789BF0AA4DA1E751`');
        $this->addSql('ALTER TABLE daily_brew_leave_requests DROP FOREIGN KEY `FK_789BF0AA82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_leave_requests DROP FOREIGN KEY `FK_789BF0AA8C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_leave_requests DROP FOREIGN KEY `FK_789BF0AAFC6B21F1`');
        $this->addSql('ALTER TABLE daily_brew_payroll_runs DROP FOREIGN KEY `FK_AEF4A5DE2FFD4FD3`');
        $this->addSql('ALTER TABLE daily_brew_payroll_runs DROP FOREIGN KEY `FK_AEF4A5DE82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_payslip_items DROP FOREIGN KEY `FK_33827A90296F5EA7`');
        $this->addSql('ALTER TABLE daily_brew_payslips DROP FOREIGN KEY `FK_20DCB4C582D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_payslips DROP FOREIGN KEY `FK_20DCB4C58C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_payslips DROP FOREIGN KEY `FK_20DCB4C5A5FC78E`');
        $this->addSql('ALTER TABLE daily_brew_roles DROP FOREIGN KEY `FK_292E8989A76ED395`');
        $this->addSql('ALTER TABLE daily_brew_shift_time_rules DROP FOREIGN KEY `FK_6D8DF402BB70BC0E`');
        $this->addSql('ALTER TABLE daily_brew_shifts DROP FOREIGN KEY `FK_8CE60D1F82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_user_settings DROP FOREIGN KEY `FK_EB53CBA0A76ED395`');
        $this->addSql('ALTER TABLE daily_brew_users DROP FOREIGN KEY `FK_8B9302A77D65B4C4`');
        $this->addSql('ALTER TABLE daily_brew_workspace_allowed_ips DROP FOREIGN KEY `FK_3BC3CA4582D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites DROP FOREIGN KEY `FK_E8D5464520F699D9`');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites DROP FOREIGN KEY `FK_E8D5464582D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites DROP FOREIGN KEY `FK_E8D546458C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites DROP FOREIGN KEY `FK_E8D54645A7B4A7E3`');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites DROP FOREIGN KEY `FK_E8D54645C58DAD6E`');
        $this->addSql('ALTER TABLE daily_brew_workspace_settings DROP FOREIGN KEY `FK_A71C938582D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_workspace_users DROP FOREIGN KEY `FK_4200BCE82D40A1F`');
        $this->addSql('ALTER TABLE daily_brew_workspace_users DROP FOREIGN KEY `FK_4200BCE8C03F15C`');
        $this->addSql('ALTER TABLE daily_brew_workspace_users DROP FOREIGN KEY `FK_4200BCEA76ED395`');
        $this->addSql('DROP TABLE daily_brew_attendance_batches');
        $this->addSql('DROP TABLE daily_brew_attendances');
        $this->addSql('DROP TABLE daily_brew_demo_sessions');
        $this->addSql('DROP TABLE daily_brew_employee_attendance_batches');
        $this->addSql('DROP TABLE daily_brew_employee_evaluations');
        $this->addSql('DROP TABLE daily_brew_employee_roles');
        $this->addSql('DROP TABLE daily_brew_employee_salaries');
        $this->addSql('DROP TABLE daily_brew_employee_scores');
        $this->addSql('DROP TABLE daily_brew_employee_templates');
        $this->addSql('DROP TABLE daily_brew_employees');
        $this->addSql('DROP TABLE daily_brew_evaluation_criterias');
        $this->addSql('DROP TABLE daily_brew_evaluation_template_criterias');
        $this->addSql('DROP TABLE daily_brew_evaluation_templates');
        $this->addSql('DROP TABLE daily_brew_leave_requests');
        $this->addSql('DROP TABLE daily_brew_payroll_runs');
        $this->addSql('DROP TABLE daily_brew_payslip_items');
        $this->addSql('DROP TABLE daily_brew_payslips');
        $this->addSql('DROP TABLE daily_brew_refresh_tokens');
        $this->addSql('DROP TABLE daily_brew_roles');
        $this->addSql('DROP TABLE daily_brew_shift_time_rules');
        $this->addSql('DROP TABLE daily_brew_shifts');
        $this->addSql('DROP TABLE daily_brew_user_settings');
        $this->addSql('DROP TABLE daily_brew_users');
        $this->addSql('DROP TABLE daily_brew_workspace_allowed_ips');
        $this->addSql('DROP TABLE daily_brew_workspace_invites');
        $this->addSql('DROP TABLE daily_brew_workspace_settings');
        $this->addSql('DROP TABLE daily_brew_workspace_users');
        $this->addSql('DROP TABLE daily_brew_workspaces');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_brew_attendance_batches (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, canonical_label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, note LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, from_date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', to_date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', workspace_id INT UNSIGNED DEFAULT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_22FA5C72B5B48B91 (public_id), UNIQUE INDEX UNIQ_ATTENDANCE_BATCH_LABEL (label, workspace_id), UNIQUE INDEX UNIQ_ATTENDANCE_BATCH_CANONICAL_LABEL (canonical_label, workspace_id), INDEX IDX_22FA5C72A76ED395 (user_id), INDEX IDX_22FA5C7282D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_attendances (id INT UNSIGNED AUTO_INCREMENT NOT NULL, employee_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED DEFAULT NULL, batch_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', attendance_date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', note LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, clock_in DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', clock_out DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, leave_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, workspace_id INT UNSIGNED DEFAULT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_CD680F1CB5B48B91 (public_id), UNIQUE INDEX UNIQ_ATTENDANCE_EMPLOYEE_DATE (employee_id, attendance_date), INDEX IDX_CD680F1C8C03F15C (employee_id), INDEX IDX_CD680F1CA76ED395 (user_id), INDEX IDX_CD680F1CF39EBE7A (batch_id), INDEX IDX_CD680F1C82D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_demo_sessions (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', device_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', active TINYINT NOT NULL, last_seen_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_76512A28B5B48B91 (public_id), UNIQUE INDEX UNIQ_DEMO_SESSION_DEVICE_ID (device_id), INDEX IDX_76512A28A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_employee_attendance_batches (attendance_batch_id INT UNSIGNED NOT NULL, employee_id INT UNSIGNED NOT NULL, INDEX IDX_5CAC43841D9718B8 (attendance_batch_id), INDEX IDX_5CAC43848C03F15C (employee_id), PRIMARY KEY (attendance_batch_id, employee_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_employee_evaluations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, employee_id INT UNSIGNED NOT NULL, evaluator_id INT UNSIGNED NOT NULL, template_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', template_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, evaluated_at DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', note LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, average_score DOUBLE PRECISION NOT NULL, workspace_id INT UNSIGNED DEFAULT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_1C4A4D25B5B48B91 (public_id), UNIQUE INDEX UQ_EMPLOYEE_EVALUATION (evaluated_at, employee_id, template_name), INDEX IDX_1C4A4D258C03F15C (employee_id), INDEX IDX_1C4A4D2543575BE2 (evaluator_id), INDEX IDX_1C4A4D255DA0FB8 (template_id), INDEX IDX_1C4A4D2582D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_employee_roles (employee_id INT UNSIGNED NOT NULL, role_id INT UNSIGNED NOT NULL, INDEX IDX_63052DE68C03F15C (employee_id), INDEX IDX_63052DE6D60322AC (role_id), PRIMARY KEY (employee_id, role_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_employee_salaries (id INT UNSIGNED AUTO_INCREMENT NOT NULL, employee_id INT UNSIGNED NOT NULL, workspace_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', base_salary NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, salary_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, effective_from DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', effective_to DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', UNIQUE INDEX UNIQ_45472EAEB5B48B91 (public_id), UNIQUE INDEX UNIQ_45472EAE8C03F15C (employee_id), INDEX IDX_45472EAE82D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_employee_scores (id INT UNSIGNED AUTO_INCREMENT NOT NULL, evaluation_id INT UNSIGNED NOT NULL, criteria_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', criteria_label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, score INT NOT NULL, weight INT NOT NULL, comment LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_4BEC1C03B5B48B91 (public_id), INDEX IDX_4BEC1C03456C5646 (evaluation_id), INDEX IDX_4BEC1C03990BEA15 (criteria_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_employee_templates (employee_id INT UNSIGNED NOT NULL, evaluation_template_id INT UNSIGNED NOT NULL, INDEX IDX_BFEBC2EF8C03F15C (employee_id), INDEX IDX_BFEBC2EF56839BCF (evaluation_template_id), PRIMARY KEY (employee_id, evaluation_template_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_employees (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, linked_user_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', first_name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, last_name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, phone_number VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dob DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', joined_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', status VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, workspace_id INT UNSIGNED DEFAULT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', shift_id INT UNSIGNED DEFAULT NULL, UNIQUE INDEX UNIQ_370C3B6FB5B48B91 (public_id), UNIQUE INDEX UNIQ_370C3B6FCC26EB02 (linked_user_id), INDEX IDX_370C3B6FA76ED395 (user_id), INDEX IDX_370C3B6F82D40A1F (workspace_id), INDEX IDX_370C3B6FBB70BC0E (shift_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_evaluation_criterias (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, canonical_label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, weight INT NOT NULL, workspace_id INT UNSIGNED DEFAULT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_F5194DE7B5B48B91 (public_id), UNIQUE INDEX UQ_EVALUATION_CRITERIA_LABEL (label, workspace_id), UNIQUE INDEX UQ_EVALUATION_CRITERIA_CANONICAL_LABEL (canonical_label, workspace_id), INDEX IDX_F5194DE7A76ED395 (user_id), INDEX IDX_F5194DE782D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_evaluation_template_criterias (id INT UNSIGNED AUTO_INCREMENT NOT NULL, template_id INT UNSIGNED NOT NULL, criteria_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', weight INT NOT NULL, UNIQUE INDEX UNIQ_AC46DABBB5B48B91 (public_id), INDEX IDX_AC46DABB5DA0FB8 (template_id), INDEX IDX_AC46DABB990BEA15 (criteria_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_evaluation_templates (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, canonical_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active TINYINT NOT NULL, workspace_id INT UNSIGNED DEFAULT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_1B36534FB5B48B91 (public_id), UNIQUE INDEX UQ_EVALUATION_TEMPLATE_NAME (name, workspace_id), UNIQUE INDEX UQ_EVALUATION_TEMPLATE_CANONICAL_NAME (canonical_name, workspace_id), INDEX IDX_1B36534FA76ED395 (user_id), INDEX IDX_1B36534F82D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_leave_requests (id INT UNSIGNED AUTO_INCREMENT NOT NULL, employee_id INT UNSIGNED NOT NULL, workspace_id INT UNSIGNED NOT NULL, requested_by_id INT UNSIGNED NOT NULL, reviewed_by_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, start_date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', end_date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', reason LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, status VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, reviewed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', review_note LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_789BF0AAB5B48B91 (public_id), INDEX IDX_789BF0AA8C03F15C (employee_id), INDEX IDX_789BF0AA82D40A1F (workspace_id), INDEX IDX_789BF0AA4DA1E751 (requested_by_id), INDEX IDX_789BF0AAFC6B21F1 (reviewed_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_payroll_runs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, workspace_id INT UNSIGNED NOT NULL, processed_by_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', period DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', status VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, processed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_AEF4A5DEB5B48B91 (public_id), UNIQUE INDEX UNIQ_PAYROLL_RUN_WORKSPACE_PERIOD (workspace_id, period), INDEX IDX_AEF4A5DE82D40A1F (workspace_id), INDEX IDX_AEF4A5DE2FFD4FD3 (processed_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_payslip_items (id INT UNSIGNED AUTO_INCREMENT NOT NULL, payslip_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, amount NUMERIC(10, 2) NOT NULL, UNIQUE INDEX UNIQ_33827A90B5B48B91 (public_id), INDEX IDX_33827A90296F5EA7 (payslip_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_payslips (id INT UNSIGNED AUTO_INCREMENT NOT NULL, payroll_run_id INT UNSIGNED NOT NULL, employee_id INT UNSIGNED NOT NULL, workspace_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', base_salary NUMERIC(10, 2) NOT NULL, total_allowances NUMERIC(10, 2) NOT NULL, total_deductions NUMERIC(10, 2) NOT NULL, net_pay NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, working_days INT NOT NULL, present_days INT NOT NULL, absent_days INT NOT NULL, late_days INT NOT NULL, paid_leave_days INT NOT NULL, unpaid_leave_days INT NOT NULL, status VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, paid_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', notes LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_20DCB4C5B5B48B91 (public_id), UNIQUE INDEX UNIQ_PAYSLIP_RUN_EMPLOYEE (payroll_run_id, employee_id), INDEX IDX_20DCB4C5A5FC78E (payroll_run_id), INDEX IDX_20DCB4C58C03F15C (employee_id), INDEX IDX_20DCB4C582D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, username VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_A69AE9B9C74F2195 (refresh_token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_roles (id INT UNSIGNED AUTO_INCREMENT NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, canonical_name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_id INT UNSIGNED NOT NULL, UNIQUE INDEX UNIQ_292E8989B5B48B91 (public_id), UNIQUE INDEX UNQ_ROLE_NAME (name, user_id), UNIQUE INDEX UNQ_ROLE_NAME_CANONICAL (canonical_name, user_id), INDEX IDX_292E8989A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_shift_time_rules (id INT UNSIGNED AUTO_INCREMENT NOT NULL, shift_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', day_of_week INT NOT NULL, start_time VARCHAR(5) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, end_time VARCHAR(5) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_6D8DF402B5B48B91 (public_id), UNIQUE INDEX UNIQ_SHIFT_DAY (shift_id, day_of_week), INDEX IDX_6D8DF402BB70BC0E (shift_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_shifts (id INT UNSIGNED AUTO_INCREMENT NOT NULL, workspace_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, grace_late_minutes SMALLINT UNSIGNED DEFAULT 0 NOT NULL, grace_early_minutes SMALLINT UNSIGNED DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_8CE60D1FB5B48B91 (public_id), INDEX IDX_8CE60D1F82D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_user_settings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, value VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_EB53CBA0B5B48B91 (public_id), UNIQUE INDEX UNIQ_SETTING_NAME (name, user_id), INDEX IDX_EB53CBA0A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_users (id INT UNSIGNED AUTO_INCREMENT NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', secret VARCHAR(225) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(180) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email_canonical VARCHAR(180) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, roles JSON NOT NULL, first_name VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, last_name VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dob DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', image_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, file_size INT DEFAULT NULL, original_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, mime_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dimensions JSON DEFAULT NULL, password VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, enabled TINYINT NOT NULL, locale VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, apple_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, current_workspace_id INT UNSIGNED DEFAULT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', google_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_8B9302A7B5B48B91 (public_id), UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL_CANONICAL (email_canonical), UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL_SECRET (secret), UNIQUE INDEX UNIQ_IDENTIFIER_APPLE_ID (apple_id), UNIQUE INDEX UNIQ_IDENTIFIER_GOOGLE_ID (google_id), INDEX IDX_8B9302A77D65B4C4 (current_workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_workspace_allowed_ips (id INT UNSIGNED AUTO_INCREMENT NOT NULL, workspace_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ip VARCHAR(45) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, label VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, is_active TINYINT NOT NULL, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_3BC3CA45B5B48B91 (public_id), INDEX IDX_3BC3CA4582D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_workspace_invites (id INT UNSIGNED AUTO_INCREMENT NOT NULL, workspace_id INT UNSIGNED DEFAULT NULL, employee_id INT UNSIGNED DEFAULT NULL, invited_by_id INT UNSIGNED DEFAULT NULL, invited_user_id INT UNSIGNED DEFAULT NULL, accepted_by_id INT UNSIGNED DEFAULT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', email VARCHAR(180) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, email_canonical VARCHAR(180) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, role VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, status VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', accepted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_E8D54645B5B48B91 (public_id), UNIQUE INDEX UNIQ_WORKSPACE_INVITE_TOKEN (token), UNIQUE INDEX UNIQ_E8D546458C03F15C (employee_id), INDEX IDX_E8D5464582D40A1F (workspace_id), INDEX IDX_E8D54645A7B4A7E3 (invited_by_id), INDEX IDX_E8D54645C58DAD6E (invited_user_id), INDEX IDX_E8D5464520F699D9 (accepted_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_workspace_settings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, workspace_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, value VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_A71C9385B5B48B91 (public_id), UNIQUE INDEX UNIQ_WORKSPACE_SETTING_NAME (name, workspace_id), INDEX IDX_A71C938582D40A1F (workspace_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_workspace_users (id INT UNSIGNED AUTO_INCREMENT NOT NULL, workspace_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', role VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, custom_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', employee_id INT UNSIGNED DEFAULT NULL, UNIQUE INDEX UNIQ_4200BCEB5B48B91 (public_id), INDEX IDX_4200BCE82D40A1F (workspace_id), INDEX IDX_4200BCEA76ED395 (user_id), INDEX IDX_4200BCE8C03F15C (employee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daily_brew_workspaces (id INT UNSIGNED AUTO_INCREMENT NOT NULL, public_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, plan VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', image_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, file_size INT DEFAULT NULL, original_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, mime_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dimensions JSON DEFAULT NULL, UNIQUE INDEX UNIQ_A26801FAB5B48B91 (public_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE daily_brew_attendance_batches ADD CONSTRAINT `FK_22FA5C7282D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_attendance_batches ADD CONSTRAINT `FK_22FA5C72A76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_attendances ADD CONSTRAINT `FK_CD680F1C82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_attendances ADD CONSTRAINT `FK_CD680F1C8C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_attendances ADD CONSTRAINT `FK_CD680F1CA76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_attendances ADD CONSTRAINT `FK_CD680F1CF39EBE7A` FOREIGN KEY (batch_id) REFERENCES daily_brew_attendance_batches (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_demo_sessions ADD CONSTRAINT `FK_8201C815A76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_employee_attendance_batches ADD CONSTRAINT `FK_5CAC43841D9718B8` FOREIGN KEY (attendance_batch_id) REFERENCES daily_brew_attendance_batches (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_attendance_batches ADD CONSTRAINT `FK_5CAC43848C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations ADD CONSTRAINT `FK_1C4A4D2543575BE2` FOREIGN KEY (evaluator_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations ADD CONSTRAINT `FK_1C4A4D255DA0FB8` FOREIGN KEY (template_id) REFERENCES daily_brew_evaluation_templates (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations ADD CONSTRAINT `FK_1C4A4D2582D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_evaluations ADD CONSTRAINT `FK_1C4A4D258C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_employee_roles ADD CONSTRAINT `FK_63052DE68C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_roles ADD CONSTRAINT `FK_63052DE6D60322AC` FOREIGN KEY (role_id) REFERENCES daily_brew_roles (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_salaries ADD CONSTRAINT `FK_45472EAE82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_salaries ADD CONSTRAINT `FK_45472EAE8C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_scores ADD CONSTRAINT `FK_4BEC1C03456C5646` FOREIGN KEY (evaluation_id) REFERENCES daily_brew_employee_evaluations (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_employee_scores ADD CONSTRAINT `FK_4BEC1C03990BEA15` FOREIGN KEY (criteria_id) REFERENCES daily_brew_evaluation_template_criterias (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_employee_templates ADD CONSTRAINT `FK_BFEBC2EF56839BCF` FOREIGN KEY (evaluation_template_id) REFERENCES daily_brew_evaluation_templates (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employee_templates ADD CONSTRAINT `FK_BFEBC2EF8C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employees ADD CONSTRAINT `FK_370C3B6F82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_employees ADD CONSTRAINT `FK_370C3B6FA76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_employees ADD CONSTRAINT `FK_370C3B6FBB70BC0E` FOREIGN KEY (shift_id) REFERENCES daily_brew_shifts (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_employees ADD CONSTRAINT `FK_370C3B6FCC26EB02` FOREIGN KEY (linked_user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_evaluation_criterias ADD CONSTRAINT `FK_F5194DE782D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_evaluation_criterias ADD CONSTRAINT `FK_F5194DE7A76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_evaluation_template_criterias ADD CONSTRAINT `FK_AC46DABB5DA0FB8` FOREIGN KEY (template_id) REFERENCES daily_brew_evaluation_templates (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_evaluation_template_criterias ADD CONSTRAINT `FK_AC46DABB990BEA15` FOREIGN KEY (criteria_id) REFERENCES daily_brew_evaluation_criterias (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_evaluation_templates ADD CONSTRAINT `FK_1B36534F82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_evaluation_templates ADD CONSTRAINT `FK_1B36534FA76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_leave_requests ADD CONSTRAINT `FK_789BF0AA4DA1E751` FOREIGN KEY (requested_by_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_leave_requests ADD CONSTRAINT `FK_789BF0AA82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_leave_requests ADD CONSTRAINT `FK_789BF0AA8C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_leave_requests ADD CONSTRAINT `FK_789BF0AAFC6B21F1` FOREIGN KEY (reviewed_by_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_payroll_runs ADD CONSTRAINT `FK_AEF4A5DE2FFD4FD3` FOREIGN KEY (processed_by_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_payroll_runs ADD CONSTRAINT `FK_AEF4A5DE82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_payslip_items ADD CONSTRAINT `FK_33827A90296F5EA7` FOREIGN KEY (payslip_id) REFERENCES daily_brew_payslips (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_payslips ADD CONSTRAINT `FK_20DCB4C582D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_payslips ADD CONSTRAINT `FK_20DCB4C58C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_payslips ADD CONSTRAINT `FK_20DCB4C5A5FC78E` FOREIGN KEY (payroll_run_id) REFERENCES daily_brew_payroll_runs (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_roles ADD CONSTRAINT `FK_292E8989A76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_shift_time_rules ADD CONSTRAINT `FK_6D8DF402BB70BC0E` FOREIGN KEY (shift_id) REFERENCES daily_brew_shifts (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_shifts ADD CONSTRAINT `FK_8CE60D1F82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_user_settings ADD CONSTRAINT `FK_EB53CBA0A76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_users ADD CONSTRAINT `FK_8B9302A77D65B4C4` FOREIGN KEY (current_workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_workspace_allowed_ips ADD CONSTRAINT `FK_3BC3CA4582D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites ADD CONSTRAINT `FK_E8D5464520F699D9` FOREIGN KEY (accepted_by_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites ADD CONSTRAINT `FK_E8D5464582D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites ADD CONSTRAINT `FK_E8D546458C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites ADD CONSTRAINT `FK_E8D54645A7B4A7E3` FOREIGN KEY (invited_by_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_workspace_invites ADD CONSTRAINT `FK_E8D54645C58DAD6E` FOREIGN KEY (invited_user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_workspace_settings ADD CONSTRAINT `FK_A71C938582D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_brew_workspace_users ADD CONSTRAINT `FK_4200BCE82D40A1F` FOREIGN KEY (workspace_id) REFERENCES daily_brew_workspaces (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE daily_brew_workspace_users ADD CONSTRAINT `FK_4200BCE8C03F15C` FOREIGN KEY (employee_id) REFERENCES daily_brew_employees (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE daily_brew_workspace_users ADD CONSTRAINT `FK_4200BCEA76ED395` FOREIGN KEY (user_id) REFERENCES daily_brew_users (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE attendance DROP FOREIGN KEY FK_6DE30D918C03F15C');
        $this->addSql('ALTER TABLE closure DROP FOREIGN KEY FK_48078DD182D40A1F');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A182D40A1F');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A1A76ED395');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A1BB70BC0E');
        $this->addSql('ALTER TABLE leave_request DROP FOREIGN KEY FK_7DC8F7788C03F15C');
        $this->addSql('ALTER TABLE shift DROP FOREIGN KEY FK_A50B3B4582D40A1F');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D382D40A1F');
        $this->addSql('ALTER TABLE workspace DROP FOREIGN KEY FK_8D9400197E3C61F9');
        $this->addSql('ALTER TABLE workspace_setting DROP FOREIGN KEY FK_4749539382D40A1F');
        $this->addSql('DROP TABLE attendance');
        $this->addSql('DROP TABLE closure');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE leave_request');
        $this->addSql('DROP TABLE shift');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE workspace');
        $this->addSql('DROP TABLE workspace_setting');
    }
}
