<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511051704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Employee.attendanceTracking enum column (full / none) for opting employees out of absent-count and discipline flags';
    }

    public function up(Schema $schema): void
    {
        // Only ADD the new column. The autogenerated diff also tried to CHANGE
        // manager_permissions to DEFAULT '[]', but MySQL rejects literal
        // defaults on JSON columns under strict mode (error 1101). The column
        // already has the correct expression default (JSON_ARRAY()) from
        // Version20260510120000, so no CHANGE is needed.
        $this->addSql('ALTER TABLE daily_brew_employees ADD attendance_tracking VARCHAR(20) DEFAULT \'full\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE daily_brew_employees DROP attendance_tracking');
    }
}
