<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511064705 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Employee.jobTitle free-text column for the day-to-day role (Cashier, Cook, Waiter, etc.).';
    }

    public function up(Schema $schema): void
    {
        // Only the new job_title column. The autogenerated diff also tried
        // to re-ADD attendance_tracking (already added by Version20260511051704)
        // and re-CHANGE manager_permissions to drop its JSON_ARRAY() default —
        // both spurious. The prior migrations are already correct in prod.
        $this->addSql('ALTER TABLE daily_brew_employees ADD job_title VARCHAR(100) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE daily_brew_employees DROP job_title');
    }
}
