controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    name_prefix: dailybrew_

dailybrew_api_v1_:
    resource:
        path: '../src/ApiController/'
        namespace: App\ApiController
        exclude: '../src/ApiController/{Checkin,Paddle}'
    type: attribute
    prefix: /api/v1/{_locale}
    requirements:
        _locale: en|fr|km
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_checkin_:
    resource:
        path: '../src/ApiController/Checkin/'
        namespace: App\ApiController\Checkin
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_webhooks_:
    resource:
        path: '../src/ApiController/Paddle/'
        namespace: App\ApiController\Paddle
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

gesdinet_jwt_refresh_token:
    path: /api/v1/token/refresh
