controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
        exclude: '../src/Controller/OAuth/'
    type: attribute
    name_prefix: dailybrew_

dailybrew_oauth_auth_:
    resource:
        path: '../src/Controller/OAuth/Auth/'
        namespace: App\Controller\OAuth\Auth
    type: attribute
    prefix: /oauth/auth
    name_prefix: dailybrew_oauth_auth_

dailybrew_oauth_connect_:
    resource:
        path: '../src/Controller/OAuth/Connect/'
        namespace: App\Controller\OAuth\Connect
    type: attribute
    prefix: /oauth/connect
    name_prefix: dailybrew_oauth_connect_

dailybrew_api_v1_:
    resource:
        path: '../src/ApiController/'
        namespace: App\ApiController
        exclude: '../src/ApiController/{Checkin,Device,Paddle,RevenueCat,Dev,BasilBook}'
    type: attribute
    prefix: /api/v1/{_locale}
    requirements:
        _locale: en|fr|km
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_device_:
    resource:
        path: '../src/ApiController/Device/'
        namespace: App\ApiController\Device
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_checkin_:
    resource:
        path: '../src/ApiController/Checkin/'
        namespace: App\ApiController\Checkin
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_webhooks_paddle_:
    resource:
        path: '../src/ApiController/Paddle/'
        namespace: App\ApiController\Paddle
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_webhooks_revenuecat_:
    resource:
        path: '../src/ApiController/RevenueCat/'
        namespace: App\ApiController\RevenueCat
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_dev_:
    resource:
        path: '../src/ApiController/Dev/'
        namespace: App\ApiController\Dev
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

dailybrew_api_v1_basilbook_:
    resource:
        path: '../src/ApiController/BasilBook/'
        namespace: App\ApiController\BasilBook
    type: attribute
    prefix: /api/v1
    name_prefix: dailybrew_api_v1_
    options:
        strict_requirements: true

gesdinet_jwt_refresh_token:
    path: /api/v1/token/refresh
