api_v1_controllers:
    resource:
        path:      ../src/ApiController/
        namespace: App\ApiController
    type:        attribute
    name_prefix: daily_brew_api_v1_
    prefix:      /api/v1/{_locale}
    locale:      en
    requirements:
        _locale: en|fr|km

controllers:
    resource:
        path:      ../src/Controller/
        namespace: App\Controller
    type: attribute

oauth_auth_controllers:
    resource:
        path:      ../src/Controller/OAuth/Auth
        namespace: App\Controller\OAuth\Auth
    type:        attribute
    name_prefix: adora_oauth_auth_
    prefix:      /oauth/auth

oauth_connect_controllers:
    resource:
        path:      ../src/Controller/OAuth/Connect
        namespace: App\Controller\OAuth\Connect
    type:        attribute
    name_prefix: adora_oauth_connect_
    prefix:      /oauth/connect
