/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleSettingsRouteImport } from './routes/console/settings'
import { Route as ConsoleDashboardRouteImport } from './routes/console/dashboard'
import { Route as CheckinQrTokenRouteImport } from './routes/checkin/$qrToken'
import { Route as ConsoleShiftsIndexRouteImport } from './routes/console/shifts/index'
import { Route as ConsoleProfileIndexRouteImport } from './routes/console/profile/index'
import { Route as ConsoleLeaveIndexRouteImport } from './routes/console/leave/index'
import { Route as ConsoleEmployeesIndexRouteImport } from './routes/console/employees/index'
import { Route as ConsoleClosuresIndexRouteImport } from './routes/console/closures/index'
import { Route as ConsoleAttendanceIndexRouteImport } from './routes/console/attendance/index'
import { Route as ConsoleEmployeesNewRouteImport } from './routes/console/employees/new'
import { Route as ConsoleEmployeesPublicIdIndexRouteImport } from './routes/console/employees/$publicId/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const CheckinQrTokenRoute = CheckinQrTokenRouteImport.update({
  id: '/checkin/$qrToken',
  path: '/checkin/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleShiftsIndexRoute = ConsoleShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleProfileIndexRoute = ConsoleProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleLeaveIndexRoute = ConsoleLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleEmployeesIndexRoute = ConsoleEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleClosuresIndexRoute = ConsoleClosuresIndexRouteImport.update({
  id: '/closures/',
  path: '/closures/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAttendanceIndexRoute = ConsoleAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleEmployeesNewRoute = ConsoleEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleEmployeesPublicIdIndexRoute =
  ConsoleEmployeesPublicIdIndexRouteImport.update({
    id: '/employees/$publicId/',
    path: '/employees/$publicId/',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/checkin/$qrToken': typeof CheckinQrTokenRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/employees/new': typeof ConsoleEmployeesNewRoute
  '/console/attendance/': typeof ConsoleAttendanceIndexRoute
  '/console/closures/': typeof ConsoleClosuresIndexRoute
  '/console/employees/': typeof ConsoleEmployeesIndexRoute
  '/console/leave/': typeof ConsoleLeaveIndexRoute
  '/console/profile/': typeof ConsoleProfileIndexRoute
  '/console/shifts/': typeof ConsoleShiftsIndexRoute
  '/console/employees/$publicId/': typeof ConsoleEmployeesPublicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/checkin/$qrToken': typeof CheckinQrTokenRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/employees/new': typeof ConsoleEmployeesNewRoute
  '/console/attendance': typeof ConsoleAttendanceIndexRoute
  '/console/closures': typeof ConsoleClosuresIndexRoute
  '/console/employees': typeof ConsoleEmployeesIndexRoute
  '/console/leave': typeof ConsoleLeaveIndexRoute
  '/console/profile': typeof ConsoleProfileIndexRoute
  '/console/shifts': typeof ConsoleShiftsIndexRoute
  '/console/employees/$publicId': typeof ConsoleEmployeesPublicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/checkin/$qrToken': typeof CheckinQrTokenRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/employees/new': typeof ConsoleEmployeesNewRoute
  '/console/attendance/': typeof ConsoleAttendanceIndexRoute
  '/console/closures/': typeof ConsoleClosuresIndexRoute
  '/console/employees/': typeof ConsoleEmployeesIndexRoute
  '/console/leave/': typeof ConsoleLeaveIndexRoute
  '/console/profile/': typeof ConsoleProfileIndexRoute
  '/console/shifts/': typeof ConsoleShiftsIndexRoute
  '/console/employees/$publicId/': typeof ConsoleEmployeesPublicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/checkin/$qrToken'
    | '/console/dashboard'
    | '/console/settings'
    | '/console/employees/new'
    | '/console/attendance/'
    | '/console/closures/'
    | '/console/employees/'
    | '/console/leave/'
    | '/console/profile/'
    | '/console/shifts/'
    | '/console/employees/$publicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/checkin/$qrToken'
    | '/console/dashboard'
    | '/console/settings'
    | '/console/employees/new'
    | '/console/attendance'
    | '/console/closures'
    | '/console/employees'
    | '/console/leave'
    | '/console/profile'
    | '/console/shifts'
    | '/console/employees/$publicId'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/checkin/$qrToken'
    | '/console/dashboard'
    | '/console/settings'
    | '/console/employees/new'
    | '/console/attendance/'
    | '/console/closures/'
    | '/console/employees/'
    | '/console/leave/'
    | '/console/profile/'
    | '/console/shifts/'
    | '/console/employees/$publicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  CheckinQrTokenRoute: typeof CheckinQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/dashboard': {
      id: '/console/dashboard'
      path: '/dashboard'
      fullPath: '/console/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/checkin/$qrToken': {
      id: '/checkin/$qrToken'
      path: '/checkin/$qrToken'
      fullPath: '/checkin/$qrToken'
      preLoaderRoute: typeof CheckinQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/shifts/': {
      id: '/console/shifts/'
      path: '/shifts'
      fullPath: '/console/shifts/'
      preLoaderRoute: typeof ConsoleShiftsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/profile/': {
      id: '/console/profile/'
      path: '/profile'
      fullPath: '/console/profile/'
      preLoaderRoute: typeof ConsoleProfileIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/leave/': {
      id: '/console/leave/'
      path: '/leave'
      fullPath: '/console/leave/'
      preLoaderRoute: typeof ConsoleLeaveIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/employees/': {
      id: '/console/employees/'
      path: '/employees'
      fullPath: '/console/employees/'
      preLoaderRoute: typeof ConsoleEmployeesIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/closures/': {
      id: '/console/closures/'
      path: '/closures'
      fullPath: '/console/closures/'
      preLoaderRoute: typeof ConsoleClosuresIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/attendance/': {
      id: '/console/attendance/'
      path: '/attendance'
      fullPath: '/console/attendance/'
      preLoaderRoute: typeof ConsoleAttendanceIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/employees/new': {
      id: '/console/employees/new'
      path: '/employees/new'
      fullPath: '/console/employees/new'
      preLoaderRoute: typeof ConsoleEmployeesNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/employees/$publicId/': {
      id: '/console/employees/$publicId/'
      path: '/employees/$publicId'
      fullPath: '/console/employees/$publicId/'
      preLoaderRoute: typeof ConsoleEmployeesPublicIdIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleEmployeesNewRoute: typeof ConsoleEmployeesNewRoute
  ConsoleAttendanceIndexRoute: typeof ConsoleAttendanceIndexRoute
  ConsoleClosuresIndexRoute: typeof ConsoleClosuresIndexRoute
  ConsoleEmployeesIndexRoute: typeof ConsoleEmployeesIndexRoute
  ConsoleLeaveIndexRoute: typeof ConsoleLeaveIndexRoute
  ConsoleProfileIndexRoute: typeof ConsoleProfileIndexRoute
  ConsoleShiftsIndexRoute: typeof ConsoleShiftsIndexRoute
  ConsoleEmployeesPublicIdIndexRoute: typeof ConsoleEmployeesPublicIdIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleEmployeesNewRoute: ConsoleEmployeesNewRoute,
  ConsoleAttendanceIndexRoute: ConsoleAttendanceIndexRoute,
  ConsoleClosuresIndexRoute: ConsoleClosuresIndexRoute,
  ConsoleEmployeesIndexRoute: ConsoleEmployeesIndexRoute,
  ConsoleLeaveIndexRoute: ConsoleLeaveIndexRoute,
  ConsoleProfileIndexRoute: ConsoleProfileIndexRoute,
  ConsoleShiftsIndexRoute: ConsoleShiftsIndexRoute,
  ConsoleEmployeesPublicIdIndexRoute: ConsoleEmployeesPublicIdIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  CheckinQrTokenRoute: CheckinQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
