/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Take over from the previous SW immediately instead of waiting for every
// tab of dailybrew.work to close. Without this pair, a deployed JS fix
// (e.g. the CustomSelect picker fix from #166) is shadowed by the stale
// precache for as long as any tab stays open — which is forever in
// practice. `skipWaiting` activates this SW the moment it finishes
// installing; `clients.claim` then makes it the controller of all open
// pages on next navigation, so the next reload pulls the new precache.
self.addEventListener('install', () => {
    void self.skipWaiting();
});
self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});

// Precache all assets generated by webpack
precacheAndRoute(self.__WB_MANIFEST);

// Cache API responses with network-first strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 5 * 60 }),
    ],
  })
);

// Cache static assets (images, fonts) with cache-first strategy
registerRoute(
  ({ request }) =>
    request.destination === 'image' ||
    request.destination === 'font',
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);
