name: Code Quality & Tests

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    quality-check:
        name:    Run Code Quality Checks
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v3
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions:  mbstring, intl, bcmath, gd, pdo, sqlite, xml, zip, curl, json, pcntl, tokenizer, ctype, iconv, session, simplexml, xmlwriter, xmlreader, dom, fileinfo, posix, pdo_sqlite, pdo_mysql
                    ini-values:  post_max_size=20M, max_execution_time=180, upload_max_filesize=20M
                    coverage:    xdebug
                env:
                    update: true

            -
                name: Install dependencies
                run:  composer install --no-progress --prefer-dist --optimize-autoloader

            -
                name: Run PHP-CS-Fixer
                run:  vendor/bin/php-cs-fixer fix --dry-run --diff

            -
                name: Run PHPStan
                run:  vendor/bin/phpstan analyse

            -
                name: Run PHPUnit
                run:  ./bin/phpunit --colors=always
