name: 'DailyBrew Application Release'

on:
    push:
        branches:
            - release

jobs:
    deploy:
        name:        'Deploy to production'
        environment: release
        runs-on:     ubuntu-latest
        steps:
            -   name: Deploy to release environment using ssh
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host:            ${{ secrets.HOST }}
                    username:        ${{ secrets.USERNAME }}
                    password:        ${{ secrets.PASSWORD }}
                    port:            ${{ secrets.PORT }}
                    command_timeout: ${{ secrets.TIMEOUT }}
                    script:          |
                                     cd ${{ secrets.PROJECT_FOLDER}}
                                     sudo git pull https://${{secrets.ACCOUNT_GITHUB_USERNAME}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{secrets.ACCOUNT_GITHUB_USERNAME}}/daily-brew.git release
                                     sudo chown -R $(whoami) ${{ secrets.PROJECT_FOLDER}}
                                     composer install --no-dev --optimize-autoloader
                                     composer dump-env prod
                                     composer dump-autoload --no-dev --classmap-authoritative
                                     sudo npm ci --legacy-peer-deps
                                     sudo npm run router:generate
                                     sudo npm run build
                                     sudo chown -R www-data:www-data ${{ secrets.PROJECT_FOLDER}}
                                     sudo systemctl restart php8.4-fpm
